site_name: Cheat Menu
site_description: Easily create a cheat menu for games!

repo_url: https://github.com/hostedposted/Chenu
repo_name: hostedposted/Chenu


theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - search.highlight
    - search.suggest
    - content.tooltips
    - navigation.top
    - navigation.tabs

plugins:
  - search

extra:
  version:
    provider: mike

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Getting Started:
    - Home: index.md
    - Getting Started: getting-started.md
  - Setup:
    - Adding Hacks: setup/adding-hacks.md